jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-concourse-build-docker-image/nginx-image

resources:
  - name: git-concourse-build-docker-image
    type: git
    source:
      uri: https://github.com/brawlerkrishna/Concourse-Build-Docker-Image.git
      branch: master

  - name: docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))


